name: Deploy to GitHub Pages

on:
  push:
    branches: [master]

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      NEXT_PUBLIC_SUPABASE_URL: https://cyyysackouocgruznqrb.supabase.co
      NEXT_PUBLIC_SUPABASE_ANON_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN5eXlzYWNrb3VvY2dydXpucXJiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI4MjU5MjUsImV4cCI6MjA1ODQwMTkyNX0.0e8Fky57O3_XPmggO9JltN4f4his76OhPag0CTZlF-0

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build Next.js site
        run: npm run build

      - name: Create .nojekyll file
        run: touch out/.nojekyll

      - name: Fix homepage redirect
        run: |
          echo "Creating direct meta refresh redirect..."
          cat > out/index.html << 'EOF'
          <!DOCTYPE html>
          <html>
          <head>
            <meta charset="utf-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <title>TaskirLiv2 - Redirecting</title>
            <meta http-equiv="refresh" content="0; URL=https://app-yaniv.github.io/taskirliv2/">
            <link rel="canonical" href="https://app-yaniv.github.io/taskirliv2/">
            <style>
              body { font-family: Arial, sans-serif; padding: 20px; text-align: center; }
              h1 { margin-top: 50px; }
              a { color: #0070f3; text-decoration: none; }
              a:hover { text-decoration: underline; }
            </style>
          </head>
          <body>
            <h1>Redirecting to TaskirLiv2...</h1>
            <p>If you are not redirected automatically, <a href="https://app-yaniv.github.io/taskirliv2/">click here</a>.</p>
          </body>
          </html>
          EOF
          echo "Created simple redirect index.html without Next.js dependencies."

      - name: Debug build output
        run: ls -la out/

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: out
          branch: gh-pages
          clean: true 