name: Deploy to GitHub Pages

on:
  push:
    branches: [master]

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      NEXT_PUBLIC_SUPABASE_URL: https://cyyysackouocgruznqrb.supabase.co
      NEXT_PUBLIC_SUPABASE_ANON_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN5eXlzYWNrb3VvY2dydXpucXJiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI4MjU5MjUsImV4cCI6MjA1ODQwMTkyNX0.0e8Fky57O3_XPmggO9JltN4f4his76OhPag0CTZlF-0

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install

      - name: Debug environment
        run: |
          echo "Current directory: $(pwd)"
          echo "Next.js version: $(npm list next | grep next)"
          echo "Repository details:"
          git remote -v
          echo "Branch details:"
          git branch -a

      - name: Build
        run: next build

      - name: Create fix-script
        run: |
          cat > fix-gh-pages.sh << 'EOF'
          #!/bin/bash
          echo "Fixing build output for GitHub Pages..."
          
          # Create .nojekyll file
          touch docs/.nojekyll
          echo "Created .nojekyll file"
          
          # Create root index.html if it doesn't exist
          if [ ! -f docs/index.html ]; then
            echo "Creating index.html in docs root"
            cat > docs/index.html << 'HTMLEOF'
          <!DOCTYPE html>
          <html>
          <head>
            <meta charset="utf-8">
            <title>Redirecting to taskirliv2</title>
            <meta http-equiv="refresh" content="0; URL=taskirliv2/">
            <link rel="canonical" href="https://app-yaniv.github.io/taskirliv2/">
          </head>
          <body>
            <p>Redirecting to <a href="https://app-yaniv.github.io/taskirliv2/">https://app-yaniv.github.io/taskirliv2/</a>...</p>
          </body>
          </html>
          HTMLEOF
          fi
          
          # Create .nojekyll in taskirliv2 directory if it exists
          if [ -d docs/taskirliv2 ]; then
            touch docs/taskirliv2/.nojekyll
            echo "Created .nojekyll in taskirliv2 directory"
            
            # Copy files from taskirliv2 to docs root
            echo "Copying index files from taskirliv2 to docs root"
            cp -r docs/taskirliv2/* docs/ || echo "Copy failed but continuing"
          fi
          EOF
          chmod +x fix-gh-pages.sh

      - name: Run fix script
        run: ./fix-gh-pages.sh

      - name: List build output
        run: |
          ls -la docs/
          echo "Checking for index.html"
          find docs -name "index.html" | xargs ls -la || echo "No index.html found"
          echo "Checking for taskirliv2 directory"
          ls -la docs/taskirliv2 || echo "taskirliv2 directory not found"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          force_orphan: true  # Creates a fresh gh-pages branch 